### ISSUE TITLE
Modifier l'icône de l'identité graphique locomokidz sur github par l'icône en pièce jointe

### ISSUE THREAD

**Issue by samcome** [locomokidz/django#101]
![mini-logotype-locomokidz](https://cloud.githubusercontent.com/assets/899141/7749467/03be143e-ffce-11e4-9dfa-23a30ecf3d27.png)

**Comment by Simon975** [comment]
![](http://3.bp.blogspot.com/-paq7B5jBcIY/TeFxzXyKiEI/AAAAAAAAAPc/xTWBmmNf1l8/s1600/f401ea605e08012ee3bf00163e41dd5b.gif)

**Comment by Simon975** [comment]
En fait je peux pas le faire: Jeff seul a les droits.
