### ISSUE TITLE
Félicitations, vous êtes désormais connecté (non !)

### ISSUE THREAD

**Issue by JeffAbrahamson** [locomokidz/django#102]
Je ne pense pas que ce soit sage que l'utilisateur soit connecté après avoir confirmé son compte.  Je préfère qu'il montre qu'il est la même personne qui s'est inscrit.  Donc je pense proposer une connexion une fois confirmé.

Questions :
* Vous êtes d'accord @Simon975 @samcome ?
* Il faut modifier le texte, au lieu de "félicitations ... connecté" plutôt "bienvenu, connectez-vous" ou autre. @AnneCecileM

**Comment by samcome** [comment]
C'est ok pour moi, proposer une connexion une fois confirmé. @JeffAbrahamson
