### ISSUE TITLE
replace colors in variables-lkz.less

### ISSUE THREAD

**Issue by samcome** [locomokidz/django#105]

**Comment by samcome** [comment]
Confirmer les couleurs, merci. @Simon975 

@lkz-pink:            #d02057;
@lkz-yellow:         #f6a63c;
@lkz-green:          #2ba3a7;
@lkz-blue:            #50c1e2;
@lkz-blue-dark:    #425672;
@lkz-orange:        #eb6045;
@lkz-gray:            #878888;

**Comment by Simon975** [comment]
Correct, sauf lkz-green:
@lkz-green: #2aa3a7;
