### ISSUE TITLE
Change {{ form.tata }} to actual input elements

### ISSUE THREAD

**Issue by JeffAbrahamson** [locomokidz/django#106]

**Comment by samcome** [comment]
Sur les pages de connexion, il manque une pratique courante.
Une case à coché 'se souvenir de moi', tu en pense quoi ?

**Comment by JeffAbrahamson** [comment]
sgtm

**Comment by samcome** [comment]
Sur la branche feature-106 @JeffAbrahamson 

Problème sur la page about.html (page contact):

- l'envois du formulaire ne fonctionne pas ? une fois validé, ajout d'erreurs de saisie au dessus des champs, alors que c'est bien remplis.
- un message de confirmation d'envoi doit apparaitre ensuite ?

Todo ! checkbox 'se souvenir de moi' (page login, dev ? ajout cookie ?)

**Comment by JeffAbrahamson** [comment]
Le problème avec about.html mérite une autre issue.  Tu peux la créer et me l'assigner, Sam?
Celle-ci reste à Sam, non?

**Comment by samcome** [comment]
issue #107 (add checkbox) #111 (bug forms about.html) @JeffAbrahamson
