### ISSUE TITLE
Password strength indicator

### ISSUE THREAD

**Issue by JeffAbrahamson** [locomokidz/django#122]
Quelques idées : 

http://www.codeproject.com/Questions/420018/Show-message-the-password-text-box-is-week-or-stro

http://stackoverflow.com/questions/22976657/basic-password-strength-validator

https://gist.github.com/Mikulas/174409786a73e201fd23

**Comment by samcome** [comment]
finalement j'ai utilisé ceci : https://github.com/ablanco/jquery.pwstrength.bootstrap
