### ISSUE TITLE
Change html error form

### ISSUE THREAD

**Issue by samcome** [locomokidz/django#131]
changer la structure ul li par un span

**Comment by JeffAbrahamson** [comment]
@samcome - ??

**Comment by samcome** [comment]
actuellement par default nous avons ceci :
<ul class="errorlist"><li>Ce champ est obligatoire.</li></ul>

le mieux serait d’avoir ceci :
<span class="error"></span>

Samuel Frémondière

linkdin : https://fr.linkedin.com/in/fremondiere <https://fr.linkedin.com/in/fremondiere>

#contact {
	Mob. 0678155348
	email.  samcome@icloud.com <mailto:samcome@icloud.com> 
	twitter.  https://twitter.com/samcome <https://twitter.com/samcome>
}

**Comment by JeffAbrahamson** [comment]
Par example, je fais submit sur le formulaire de contact sans remplir un champ?

**Comment by samcome** [comment]
oui, c’est pas top d’avoir un <ul><li> juste pour une info, un span serait mieux

Samuel Frémondière

linkdin : https://fr.linkedin.com/in/fremondiere <https://fr.linkedin.com/in/fremondiere>

#contact {
	Mob. 0678155348
	email.  samcome@icloud.com <mailto:samcome@icloud.com> 
	twitter.  https://twitter.com/samcome <https://twitter.com/samcome>
}
