### ISSUE TITLE
Vérifier le texte en haut de k/trip/results.

### ISSUE THREAD

**Issue by JeffAbrahamson** [locomokidz/django#147]
J'ai légèrement changé la template kernel/templates/trip/results.html pour qu'il marche.  Mais peut-être le texte et formatting pourraient être mieux.

    Vous avez proposé un voyage de Nantes à Paris le 16-07-2015.
    Vous êtes le premier à proposer ce trajet et date.

    Chaque jour, de nouveaux parents nous rejoignent.

@AnneCecileM @samcome

**Comment by AnneCecileM** [comment]
@samcome peux-tu reprendre le texte rédigé l'autre jour avec toi qui concerne la demande "je cherche ce trajet" et le mettre pour cette recherche-ci aussi. (si il y a un truc qui cloche, je le modifierai qd je le verrai). Merci.
