### ISSUE TITLE
Envoyer un mail a Simon et Anne C quand locomokidz est live

### ISSUE THREAD

**Issue by Simon975** [locomokidz/django#156]
Merci!

**Comment by JeffAbrahamson** [comment]
Et voilà !

**Comment by Simon975** [comment]
Euh, j'ai toujours la vieille landing page...

*Simon Papon*

Designer

simonpapon.com
<http://simonpapon.com/?utm_source=Mail%20signature&utm_medium=Mail&utm_campaign=Design%20d%27identit%C3%A9s>
07 60 43 53 72

2015-07-07 11:36 GMT+02:00 Jeff Abrahamson <notifications@github.com>:

**Comment by samcome** [comment]
http://beta13.locomokidz.com/ <http://beta13.locomokidz.com/>

Samuel Frémondière




#contact {
	Mob. 06 78 15 53 48
	email.  sam@locomokidz.com <mailto:samcome@icloud.com> 
}

**Comment by Simon975** [comment]
Oui d'accord mais qu'en est-il de locomokidz.com? Il faut que l'ancienne
page disparaisse, non?

*Simon Papon*

Designer

simonpapon.com
<http://simonpapon.com/?utm_source=Mail%20signature&utm_medium=Mail&utm_campaign=Design%20d%27identit%C3%A9s>
07 60 43 53 72

2015-07-07 13:52 GMT+02:00 Samuel Frémondière <notifications@github.com>:

**Comment by JeffAbrahamson** [comment]
Oui, ça s'appelle testing.  ;-)

Je constate deux bogues d'AC, deux de moi (y compris le 500).
Un environnement de prod ne fonctionne pas exactement comme celui de dev.

Jeff Abrahamson
+33 6 24 40 01 57
+44 7920 594 255    <-- only if I'm in the UK

http://jeff.purple.com/
http://blog.purple.com/jeff/

**Comment by Simon975** [comment]
Ok, donc on est d'accord: locomokidz.com n'est pas encore *vraiment* live.
Sorry, just keeping you under pressure.

*Simon Papon*

Designer

simonpapon.com
<http://simonpapon.com/?utm_source=Mail%20signature&utm_medium=Mail&utm_campaign=Design%20d%27identit%C3%A9s>
07 60 43 53 72

2015-07-07 14:24 GMT+02:00 Jeff Abrahamson <notifications@github.com>:

> Oui, ça s'appelle testing. ;-)
>
> Je constate deux bogues d'AC, deux de moi (y compris le 500).
> Un environnement de prod ne fonctionne pas exactement comme celui de dev.
>
> Jeff Abrahamson
> +33 6 24 40 01 57
> +44 7920 594 255 <-- only if I'm in the UK
>
> http://jeff.purple.com/
> http://blog.purple.com/jeff/
>

**Comment by JeffAbrahamson** [comment]
You so don't want "really live" without all of us testing it.
Like serving 500's for several hours today.
;-)

Jeff Abrahamson
+33 6 24 40 01 57
+44 7920 594 255    <-- only if I'm in the UK

http://jeff.purple.com/
http://blog.purple.com/jeff/

2015-07-07 15:29 GMT+02:00 Simon Papon <notifications@github.com>:

> Ok, donc on est d'accord: locomokidz.com n'est pas encore *vraiment* live.
> Sorry, just keeping you under pressure.
>
> *Simon Papon*
>
> Designer
>
> simonpapon.com
> <
> http://simonpapon.com/?utm_source=Mail%20signature&utm_medium=Mail&utm_campaign=Design%20d%27identit%C3%A9s
> >
> 07 60 43 53 72
>
> 2015-07-07 14:24 GMT+02:00 Jeff Abrahamson <notifications@github.com>:
>
> > Oui, ça s'appelle testing. ;-)
> >
> > Je constate deux bogues d'AC, deux de moi (y compris le 500).
> > Un environnement de prod ne fonctionne pas exactement comme celui de dev.
> >
> > Jeff Abrahamson
> > +33 6 24 40 01 57
> > +44 7920 594 255 <-- only if I'm in the UK
> >
> > http://jeff.purple.com/
> > http://blog.purple.com/jeff/
> >

**Comment by Simon975** [comment]
Yeah I know. I'm just saying the issue isn't closed.
