### ISSUE TITLE
Créer un onglet "partenaires"

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#35]
A créer sur le site OU sur le blog (à voir) pour encourager le partenariat avec des boites qui ont notre même cible et faire grossir notre masse utilisateurs.

**Comment by JeffAbrahamson** [comment]
@Simon975 Comment vois-tu l'aspect visuel?

**Comment by JeffAbrahamson** [comment]
On le fera dans un premier temps en hard.  Je bascule sur Wish List en attendant notre prioritisation.
