### ISSUE TITLE
Créer une rubrique "ils nous soutiennent" 

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#36]
Elle peut se trouver dans le footer (comme chez certains de nos concurrents) ou ailleurs. L'idée c'est d'y mettre les articles de presse, émissions TV et autre qui parlent de nous (possibilité de mettre le logo du support presse, un lien, une image, voire un vidéo créée par nos soins ex : interview d'un avocat)

**Comment by JeffAbrahamson** [comment]
@AnneCecileM Ce serait bien de définir un peu plus.  On y ajoute du contenu comment, par exemple?  Il aura quoi comme look?

**Comment by AnneCecileM** [comment]
Ca pourrait être en bas de page (cf pj tirée de là http://www.covoiturage.fr/ ) avec un lien vers l'article (ou la video ou autre) quand on clique dessus. Dans l'idéal, on pourrait choisir les titres (logos) qui figurent sur ce bas de page. La page vers laquelle les liens pointent pourrait, elle, contenir plus de contenu, éventuellement en les classant par rubrique (TV, radio, vidéo, autre). Je pense que l'ensemble de ces éléments pourraient faire partie du blog (que j'appelle moi "actualités)
![ils nous soutiennent](https://cloud.githubusercontent.com/assets/10826446/6981703/9639127a-da06-11e4-8a3c-980abf1dee8b.png)

**Comment by AnneCecileM** [comment]
Sur l'image que je t'ai mise c'est titré "la presse parle de nous". Perso je préfère la formule "ils nous soutiennent" mais le principe reste le même.

**Comment by JeffAbrahamson** [comment]
Dans un premier temps, nous pouvons faire ça en hard (c-à-d, pas gérer par la base de donneés).  Je met donc sur Wish List pour plus tard.
