### ISSUE TITLE
Bug "en savoir plus"

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#39]
le bouton "s'inscrire" en bas de page ne fonctionne pas

**Comment by JeffAbrahamson** [comment]
Aucune page n'a un bouton "s'inscrire"en base de page.

Le texte "en savoir plus" n'existe que sur le landing page.  Il dirige l'utilisateur vers /k/faq.

J'assigne à Anne-Cécile pour plus de précision.
