### ISSUE TITLE
Besoin de numéro de téléphone pour la page de contacte

### ISSUE THREAD

**Issue by JeffAbrahamson** [locomokidz/django#44]
06 (78)^4 existe-t-il?

**Comment by AnneCecileM** [comment]
Oui, mais je ne le connais pas. C'est Simon qui a pris l'abonnement.

**Comment by JeffAbrahamson** [comment]
C'est bien le 06 78 78 78 78 ?  @AnneCecileM

**Comment by AnneCecileM** [comment]
Je viens d'appeler et manifestement ce n'est pas nous à ce numéro. C'est @Simon975 qui a pris l'abonnement et qui est pour l'instant, le seul à connaitre le numéro. :-(
