### ISSUE TITLE
Changer toute occurrence du mot "blog" en "actualité".

### ISSUE THREAD

**Issue by JeffAbrahamson** [locomokidz/django#50]
@AnneCecileM

**Comment by JeffAbrahamson** [comment]
"Actualité" suggère que les articles disparaissent (de vue, au moins) quand ils ne sont plus actuels.  "Blog" suggère que les articles restent.  Qu'est-ce qui est le but du blog?

**Comment by AnneCecileM** [comment]
Remarque pertinente en effet. 
Du coup je suggère locomoblog parce que, vraiment, je trouve l'appellation "blog" très galvaudée (en plus, elle évoque pour moi le passionné de patchwork ou de pêhce à la ligne qui nous fait part de ses trouvailles). 
Si c'est pertinent, au niveau de l'url (j'ai l'impression de dire un gros mot), peut-on mettre les mots :  enfant-parent-voyage" ou la phrase "pour-les-enfants-et-parents-en-voyage" ou encore "pour-les-enfants-et-parents-qui-voyagent" (je ne connais pas trop l'importance de ces mots mais s'ils servent aux moteurs de recherche, je peux imaginer qu'on tape plus "voyage" que "voyagent". Cela dit, là c'est à 100% toi le super pro @JeffAbrahamson

**Comment by JeffAbrahamson** [comment]
Donc c'est le texte en haut qui doit changer de blog à locomoblog?  Pour le sens, je l'aime bien.  Ça ne fait pas trop de locomo?

Pour l'URL, tu veux http://locomokidz.com/locomoblog/ ?

Et puis, pour-les-enfants-et-parents-en-voyage, c'est où?

**Comment by AnneCecileM** [comment]
locomoblog c'est pour l'onglet. (accueil/ locomoblog/ en savoir plus/ contact/ connexion)
pour l'url, il me semblait que certains sites ont des adresses plus descriptions que nominatives mais peut-être est-ce, soit has been, soit inutile. Encore une fois, là dessus c'est toi le pro.
