### ISSUE TITLE
Offer password forgotten on password change page.

### ISSUE THREAD

**Issue by JeffAbrahamson** [locomokidz/django#52]

**Comment by JeffAbrahamson** [comment]
@sam, tu vois comment le faire?

**Comment by samcome** [comment]
je comprend pas bien la demande @JeffAbrahamson 
tu peux expliquer ?

**Comment by JeffAbrahamson** [comment]
Sur chaque page où on te demande ton mot de passe (à part pour la création de compte), ce serait bien d'avoir un lien pour changer son mot de passe.  Ceci n'est pas actuellement le cas pour la page où on change son mot de passe.  Il suffit de copier le liens d'une autre telle page, puis de le formatter correctement comme tu vois nécessaire.

Et dans tous les cas, sans doute, le formattage que j'ai fait est nul...

**Comment by JeffAbrahamson** [comment]
http://localhost:8000/accounts/password/change/
