### ISSUE TITLE
Need js date chooser for birthday

### ISSUE THREAD

**Issue by JeffAbrahamson** [locomokidz/django#53]

**Comment by samcome** [comment]
j'ai trouvé ceci qui est plutôt complet, multi-langue et avec une communauté d'utilisateurs importante.
https://github.com/eternicode/bootstrap-datepicker
Quand pense-tu ? tu me dit et je met les sources en place pour l'utilisation.

**Comment by JeffAbrahamson** [comment]
LGTM, si on peut faire le "npm install" une fois puis git commit et pas pour chaque dev, chaque instance.

**Comment by samcome** [comment]
Le npm install c'est pour grunt @JeffAbrahamson ? (grunt c'est un système d'automatisation js comme gulp, non compatible), il est utilisé pour le développement du repositorie, pas pour son utilisation.
Donc pas possible de faire un npm install, je dois mettre les sources en manuel.

**Comment by samcome** [comment]
j'ai installé les sources du plugin bootstrap-datepicker dans le dossier 'src'.

- src/less/plugins/datepicker3.less
- src/js/plugins/bootstrap-datepicker.js
- src/js/plugins/locales/*js

J'ai modifié le gulp.js pour le traitement vers le dossier static des sources

Après le traitement gulp, il crée un dossiers 'locales' avec les sources minifiés de languages (comme ici https://github.com/eternicode/bootstrap-datepicker/tree/master/dist/locales)

Le chemin est: kernel/static/locales/*.min.js
En local j'ai donc 64 fichiers js minifiés de languages dans ce dossier

Je voudrais savoir si il y avait quelques chose de bloquant (par exemple dans le gitignore ? ou autre ?) git ne vois pas ce nouveau dossier 'locales' dans kernel/static/
Je ne peux pas le pusher, je comprend pas.
Une idée ? @JeffAbrahamson

**Comment by JeffAbrahamson** [comment]
Ah, marrant.  J'ai modifié .gitignore, merge master dans ta branche.

**Comment by samcome** [comment]
Il y avait également un dossier media dans le gitignore, il n'existe pas pour le moment, est-ce une bonne pratique que de l'utilisé pour les images ou autre ?

**Comment by JeffAbrahamson** [comment]
Qu'est-ce qui est le chemin exacte qui est toujours ignoré incorrectement?

/media existe en production, c'est le répertoire où vont les fichiers téléchargés.

**Comment by samcome** [comment]
non, c'est bon depuis que tu as autorisé static. Il me reste un test js pour voir si le plugin fonctionne.
