### ISSUE TITLE
mail de confirmation d'inscription + email d'expédition

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#55]
La page est a simplifier. (cf saisie écran)
![mail inscription](https://cloud.githubusercontent.com/assets/10826446/7210345/449c7212-e551-11e4-8ead-8e5986c347c4.png)
On peut noter simplement :
Votre inscription à locomokidz est presque terminée. il ne vous reste plus qu'à cliquer sur ce lien et ce sera fait. A tout de suite... http://locomokidz.com:49171/accounts/activate/ad5cbbdee80057eec9f34c3e3bc337f499aff993/. 
(ce lien restera valable pendant 15 jours). 

D'autre part, est-ce que le mail d'envoi restera locomobot@locomokidz? inscription@locomokidz ou queque chose du genre serait-il possible?

**Comment by JeffAbrahamson** [comment]
Fait.
Et #69 pour suivre.

LocomoBot...c'est un peu geek.  C'est important, par contre, que ce soit clair que ce n'est pas un humain.
