### ISSUE TITLE
Page "féliciations, vous êtes inscrit"

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#56]
1 - Mon nom à coté de bonjour a disparu (cf saisie écran)
2 - une fois qu'on m'a félicitée, je reste un peu perdue au milieu de cette grande page. j'imagine que j'y trouverai très vite un lien vers la page des trajets, une fois qu'elle existera. C'est exact? 
En attendant, peut-être qu'un message "coming soon" me rassurerait du type 
"D'ci quelques jours (ou semaine), vous pourrez compléter votre profil et rechercher un premier trajet. En attendant, suivez nous sur Facebook et Twitter. Toutes les informations vous y seront communiquées"... 
A voir si c'est compliqué à mettre en place...
![bonjour](https://cloud.githubusercontent.com/assets/10826446/7210496/846c6b76-e552-11e4-9a74-05b3b9125141.png)

**Comment by JeffAbrahamson** [comment]
1.  #67

2. Oui, exacte.  En plus, ce serait bien qu'on demande l'accord de l'utilisateur pour lui contacter par mél !  Et #68.

**Comment by AnneCecileM** [comment]
Répondu sur l'autre issue #68
