### ISSUE TITLE
modifier mon profil (orthographe + contenu)

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#57]
profil s'écrit sans "e" à la fin
En l'occurrence, c'est la première fois que je le remplis. Je préfèrerais donc écrire "créer mon profil".
On ne demande pas les noms et prénoms à ce stade? (avec la possibilité de les modifier plus tard car certains vont noter des faux à ce stade là) Ca me semble bien, ne serait-ce que pour être appelée par mon prénom quand je me logue. What do you think?

**Comment by JeffAbrahamson** [comment]
Quand j'ai changer pour loguer par email plutôt que par nom d'utilisateur, c'est une bogue qui s'est introduit.  Le nom et prénom sont maintenant demandés.
