### ISSUE TITLE
Photo upload in profile

### ISSUE THREAD

**Issue by JeffAbrahamson** [locomokidz/django#6]

**Comment by JeffAbrahamson** [comment]
@samcome   {{ profile.picture }}

**Comment by samcome** [comment]
ce snippet ne donne rien.

**Comment by JeffAbrahamson** [comment]
J'ai fait un push sur master qui doit aider.  Puis, il y a quelques détails sur le téléchargement en général que je ne comprend pas encore à 100%...

Par exemple, le numéro 7 [ici](http://stackoverflow.com/questions/5871730/need-a-minimal-django-file-upload-example).  (Image est dérivé de File.)

Pour référence, [Managing files](https://docs.djangoproject.com/en/1.8/topics/files/).

**Comment by JeffAbrahamson** [comment]
@samcome Je trouve dans les docs :

The form must have enctype-attribute set to "multipart/form-data" and method set to "post" to make upload to Django possible. See [File Uploads](https://docs.djangoproject.com/en/dev/topics/http/file-uploads/) documentation for details.

**Comment by JeffAbrahamson** [comment]
OK, @samcome , à toi.
