### ISSUE TITLE
rejoignez-nous

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#60]
Je peux cliquer dessus alors que je suis déjà loguée.

**Comment by JeffAbrahamson** [comment]
URL?

**Comment by AnneCecileM** [comment]
http://locomokidz.com:49171/k/faq je pense que c'était là. Tu as dû travailer dessus. C'est sans doute pour cela que je ne peux plus cliquer sur "s'inscrire" quand je suis loguée. Peut-être serait-ce plus clair que ce bouton ne soit pas visible dans ce cas.
