### ISSUE TITLE
erreur d'identifiant

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#61]
Le texte actuel est celui-là __all__

    Vos identifiants n'étaient pas reconnus. Merci de vérifier que votre adresse mél et mot de passe sont correct. Faites attention aux majuscule et minuscule.
Le remplacer par : 
Oups, nous n'avons pas reconnu vos identifiants. Vérifiez que vous avez tapé correctement vos mail et mot de passe. Attention aux majuscules et minuscules. Parfois, une petite erreur se cache de ce coté-là.

**Comment by JeffAbrahamson** [comment]
Le __all__ est également une bogue.  Cf. #65.
