### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#62]
1 - on peut accéder à "nous contacter" sans être logué. C'est voulu?

2 - les nouveaux textes de cette page n'ont pas été mis en ligne. 
Les voici à nouveau (avec de toutes dernières modifs) : 
Votre avis compte beaucoup pour nous. Vous avez des questions à nous poser, des envies ou des remarques à nous soumettre? N’hésitez pas à nous laisser un message.
Vous préférez nous appeler? C’est possible aussi : 06.78.78.78.78

**Comment by JeffAbrahamson** [comment]
1. Oui, on essaie de mettre le minimum de barrière.  Et si un future locomoparent veut demander un renseignement avant de s'inscrire ?  Par contre, peut-être on doit faire quelque chose pour leur encourager à s'inscrire avant?  Pour @Simon975 / #64.

**Comment by JeffAbrahamson** [comment]
Fait.  Par contre, et en référence à (1), je supprime le numéro de téléphone pour les utilisateurs anonymes.

**Comment by AnneCecileM** [comment]
Ca me semble très bien comme ça en effet.
