### ISSUE TITLE
Le bouton "bonjour," est un peu nulle

### ISSUE THREAD

**Issue by JeffAbrahamson** [locomokidz/django#67]

**Comment by samcome** [comment]
C'est à dire ? plus de précision ? merci. @Simon975 @JeffAbrahamson 
![locomokidz](https://cloud.githubusercontent.com/assets/899141/7734502/a6c4bc84-ff36-11e4-9a12-915c2c40334a.png)

**Comment by JeffAbrahamson** [comment]
En haut à droite dans l'image, "Accueil ... Blog ... Esp ... Contact ... Bonjour".
Ce "bonjour" ne me dit pas ce que je peux espérer trouver en dessous.

**Comment by Simon975** [comment]
Il devrait dire "Bonjour, Jeff". Ce qui en dit plus.

*Simon Papon*

Designer

simonpapon.com
<http://simonpapon.com/?utm_source=Mail%20signature&utm_medium=Mail&utm_campaign=Design%20d%27identit%C3%A9s>
07 60 43 53 72
