### ISSUE TITLE
mise à jour mot de passe

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#71]
@JeffAbrahamson 
1 - certains mots sur le site sont restés en anglais "login" à la place de "me connecter" et "change my password" à remplacer par "changer de mot de passe" http://locomokidz.com:49171/accounts/password/reset/confirm/NQ/411-c2e33cb0aff8e4de3c3c/
2 - le mail reçu doit être modifié(cf pièce jointe)
    a - objet du mail = nouveau mot de passe sur locomokidz
    b- corps de mail 
    b1 - peut-on supprimer cette ligne :  This is locomokidz/templates/registration/password_reset_email.html.
    b2 - remplacer la phrase Au cas où vous l'auriez oublié, votre adresse mél c'est: annececilesmichelet@gmail.com par "juste pour mémo, vous vous êtes connecté avec le mail annececilesmichelet@gmail.com
     B3 replacer la signature actuelle (The locomokidz.com team) par " la locomoteam "
![mail new password](https://cloud.githubusercontent.com/assets/10826446/7221260/dd87883e-e6e3-11e4-8729-063c4db0ade6.png)

**Comment by JeffAbrahamson** [comment]
C'est fait.  Mais la #73 nous rappelle de vérifier tous concernant les mots de passe en menu détail.  C'est gérer souvent par le framework, ce qui fait qu'il y a de l'anglais caché, parfois simplement dans les messages d'erreur.

**Comment by JeffAbrahamson** [comment]
Ah, mince, ma façon de le faire à désactiver le système de traduction automatique que fournit django.  En plus, le problème, à sa base, est que django ne savait pas qu'il était en France.

Je mettrai une petite heure pour comprendre le système de traduction / I18n / L10n de django, puis je m'occupe de la suite de celle-ci.

**Comment by JeffAbrahamson** [comment]
Je vais fermer.  Ou bien nous utilisons un blog façon wordpress ou autre, ou bien nous utilisons un truc django comme zinnia.
