### ISSUE TITLE
Tester en mode production

### ISSUE THREAD

**Issue by JeffAbrahamson** [locomokidz/django#72]
Il y a milles petites différences entre le mode testing et le mode production.  Par exemple, le comportement lors d'une erreur.  Mais aussi la façon de servir les images et autres.  Surtout puisque c'est la première fois qu'on passe en prod, on est obligé de tester un peu plus en mode prod.  Ça nous impliquera tous.  @AnneCecileM @Simon975 

Pour l'instant, on teste en mode dev parce que (1) c'est plus facile à gérer et (2) quand il y une erreur, j'ai plus de visibilité dedans, pas juste en "500 - une erreur s'est produit sur le serveur".

**Comment by AnneCecileM** [comment]
OK, testons encore et encore !

**Comment by JeffAbrahamson** [comment]
En cours aussi longtemps que le site existe, bien sûr, mais censé fermable.
