### ISSUE TITLE
locomoblog - liens hypertexte

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#76]
C'est moi qui ne la trouve pas ou bien on n'a pas (encore) la possibilité de mettre des liens hypertextes dans les articles du blog. Ca me semble important ça, du coup. @JeffAbrahamson

**Comment by JeffAbrahamson** [comment]
Je vais fermer.  Ou bien nous utilisons un blog façon wordpress ou autre, ou bien nous utilisons un truc django comme zinnia.
