### ISSUE TITLE
blog : dates et modifications

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#81]
1 - Je viens de me rendre compte que si je modifier mon texte, je suis obligée de mettre la date du jour pour que le site tiennent compte de ces modifications. C'est un peu embêtant.
2 - pourrai-je avoir un calendrier qui s'affiche sur la case où je dois noter la date ainsi qu'une case "aujourd'hui". C'est une question de secondes pour moi mais à force, ça peut devenir utile.

**Comment by JeffAbrahamson** [comment]
Je vais fermer.  Ou bien nous utilisons un blog façon wordpress ou autre, ou bien nous utilisons un truc django comme zinnia.
