### ISSUE TITLE
Mail de relance avant voyage (contenu)

### ISSUE THREAD

**Issue by AnneCecileM** [locomokidz/django#83]
s'inspirer du doc en pj
![oui car](https://cloud.githubusercontent.com/assets/10826446/7386754/8cb2e900-ee57-11e4-8092-402bdce8e71a.png)
PS : @samcome @JeffAbrahamson je n'ai pas encore compris qui, ce type de technique concerne. N'héistez pas à vous "disassigner" si ça ne vous concerne pas.

**Comment by samcome** [comment]
Qui s'occupe de l'écriture des contenus ?
@Simon975 @JeffAbrahamson @AnneCecileM

**Comment by JeffAbrahamson** [comment]
pour le texte, voir avec @AnneCecileM
