### ISSUE TITLE
HTML rewriting email_base

### ISSUE THREAD

**Issue by samcome** [locomokidz/django#91]

**Comment by samcome** [comment]
Est-ce un résultat satisfaisant pour la beta ? 
C'est un test de réception d'email testé sur gmail.

@JeffAbrahamson @Simon975 @AnneCecileM 
![capture d ecran 2015-05-13 a 11 26 18](https://cloud.githubusercontent.com/assets/899141/7734542/ee673a44-ff36-11e4-964b-7507689c82e4.png)

**Comment by JeffAbrahamson** [comment]
lgtm
(= looks good to me = ça a l'air bon pour moi)

**Comment by Simon975** [comment]
lgtm2

*Simon Papon*

Designer

simonpapon.com
<http://simonpapon.com/?utm_source=Mail%20signature&utm_medium=Mail&utm_campaign=Design%20d%27identit%C3%A9s>
07 60 43 53 72

2015-05-22 10:40 GMT+02:00 Jeff Abrahamson <notifications@github.com>:

**Comment by AnneCecileM** [comment]
1 - dans la phrase "votre inscription à Locomokidz", j'ai toujours un doute quant à la présence d'une capitale en début de la marque locomokidz. @Simon975 , peux-tu me/ nous dire ce qu'il en est s'il te plait?
2 - j'enlèverais bien "en tous cas" en noterais simplement "il restera valable pendant X jours"
3 - dans la mesure où ce bout de phrase concerne ce qui est noté au dessus, je ne sauterais pas de ligne.

**Comment by samcome** [comment]
La question se pose sur le site entier pour Locomokidz ou locomokidz ? @Simon975

**Comment by Simon975** [comment]
Locomokidz avec une majuscule. Seul le logo n'en a pas. 
Et sauf exception auxquelles je ne pense pas!

**Comment by samcome** [comment]
Reste la modification 2 et 3 de AnneCecile
